### ISSUE TITLE
PHP8 Compatability

### ISSUE THREAD

**Issue by terrypro68** [cyberhobo/geo-mashup-custom#1]
File: geo-mashup-custom.php

PHP4 Constructor is used: 
_function GeoMashupCustom() {_

After replacing it with the line:
_function __construct() {_

the plugin seems start working fine.

**Comment by cyberhobo** [comment]
Thank you! This was done in https://github.com/cyberhobo/geo-mashup-custom/commit/10b002803d2ccbe9f9ee11f10a51766d45434b8f and released as https://github.com/cyberhobo/geo-mashup-custom/releases/tag/1.0.1.
